Added defaults for cronjob role. Added ecommerce-theme role.

diff --git a/playbooks/roles/credentials/defaults/main.yml b/playbooks/roles/credentials/defaults/main.yml
--- a/playbooks/roles/credentials/defaults/main.yml
+++ b/playbooks/roles/credentials/defaults/main.yml
@@ -141,8 +141,33 @@ CREDENTIALS_ENABLE_NEWRELIC_DISTRIBUTED_TRACING: false
 credentials_post_migrate_commands:
   - command: './manage.py create_or_update_site --site-id=1 --site-domain={{ CREDENTIALS_DOMAIN }} --site-name="Open edX" --platform-name="Open edX" --company-name="Open edX" --lms-url-root={{ CREDENTIALS_LMS_URL_ROOT }} --catalog-api-url={{ CREDENTIALS_DISCOVERY_API_URL }} --tos-url={{ CREDENTIALS_LMS_URL_ROOT }}/tos --privacy-policy-url={{ CREDENTIALS_LMS_URL_ROOT }}/privacy --homepage-url={{ CREDENTIALS_LMS_URL_ROOT }} --certificate-help-url={{ CREDENTIALS_LMS_URL_ROOT }}/faq --records-help-url={{ CREDENTIALS_LMS_URL_ROOT }}/faq --theme-name=openedx'
     when: '{{ credentials_create_demo_data }}'
-credentials_cronjob_auto: []
+#default cronjob task. Warning - any of your tasks will override it!
+credentials_cronjob_auto: 
+  - script: |
+      #!/usr/bin/env bash
 
+      if ! test -x /edx/bin/python.credentials -o -x /edx/bin/python.edxapp ; then
+        # for multi-instance installations: do nothing on non edxapp instances
+        exit
+      fi
+
+      SHELL=/bin/bash
+      CREDENTIALS_CFG=/edx/etc/credentials.yml
+      LOG_FILE=/edx/var/log/update_credentials/edx.log
+      mkdir -p `dirname ${LOG_FILE}`
+      exec &>> ${LOG_FILE}
+      exec 2>&1
+      export SHELL
+      export CREDENTIALS_CFG
+
+      if test -x /edx/bin/python.credentials ; then
+        sudo -Eu credentials /edx/app/credentials/venvs/credentials/bin/python /edx/app/credentials/credentials/manage.py copy_catalog --settings=credentials.settings.production
+      else
+        echo "credentials service not found" >&2
+      fi
+    name: "credentials copy catalog"
+    filename: "update_credentials.sh"
+    minute: "*/10"
 
 # Remote config
 CREDENTIALS_HERMES_ENABLED: "{{ COMMON_HERMES_ENABLED }}"
